name: Deploy to GitHub Pages

on:
  push:
    branches:
      # - main
      - xin
      - test
      
jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ›ï¸ Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history so that last modified date-times are accurate

      - name: ğŸ Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: ğŸ§³ Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: ğŸ‘·â€ init and preprocessing
        shell: bash
        run: |
          pip install --upgrade pip
          pip install invoke
          invoke init
          invoke preprocessing
      
      - name: ğŸ”§ Build HTML (en)
        run: |

          invoke intl.language -l zh_CN
          
          cd docs
          make html
      
      - name: ğŸ”§ Build HTML (zh_CN ...)
        run: |
          cd docs
          sphinx-build -D language=zh_CN -b html ./ ../output/html/zh_CN

      - name: ğŸš€ Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output/html/

      - name: delete temp
        run: |
          rm -rf Nuitka-main/
          rm -rf Nuitka-develop/
          rm -rf Nuitka-factory/
          rm -rf output/doctrees/
          rm -rf docs/images/
          rm -rf docs/doc/